/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RelationDto {
  authorId?: number;
  bookId: number;
  publisherId?: number;
  seriesId?: number;
}
