/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeriesDto {
  seriesBooks?: Array<string>;
  seriesId: number;
  seriesName?: string;
  seriesNumberOfEntries?: number;
}
