/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';


export interface GetBookByAny$Params {
  bookTitle?: string;
  bookId?: number;
  bookEdition?: number;
  bookPublisherName?: string;
  bookAuthor?: string;
}

export function getBookByAny(http: HttpClient, rootUrl: string, params?: GetBookByAny$Params, context?: HttpContext): Observable<StrictHttpResponse<{}>> {
  const rb = new RequestBuilder(rootUrl, getBookByAny.PATH, 'get');
  if (params) {
    rb.query('bookTitle', params.bookTitle, {});
    rb.query('bookId', params.bookId, {});
    rb.query('bookEdition', params.bookEdition, {});
    rb.query('bookPublisherName', params.bookPublisherName, {});
    rb.query('bookAuthor', params.bookAuthor, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{}>;
    })
  );
}

getBookByAny.PATH = '/api/books/search/by';
