/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetBookByPubEdiEntry$Params {
  bookPublisherName: string;
  bookEdition: number;
  bookEntryInSeries: number;
}

export function getBookByPubEdiEntry(http: HttpClient, rootUrl: string, params: GetBookByPubEdiEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, getBookByPubEdiEntry.PATH, 'get');
  if (params) {
    rb.query('bookPublisherName', params.bookPublisherName, {});
    rb.query('bookEdition', params.bookEdition, {});
    rb.query('bookEntryInSeries', params.bookEntryInSeries, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

getBookByPubEdiEntry.PATH = '/api/books/search/for';
