/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {PublisherDto} from '../../models/publisher-dto';

export interface GetPublisherById$Params {
  publisherId: number;
}

export function getPublisherById(http: HttpClient, rootUrl: string, params: GetPublisherById$Params, context?: HttpContext): Observable<StrictHttpResponse<PublisherDto>> {
  const rb = new RequestBuilder(rootUrl, getPublisherById.PATH, 'get');
  if (params) {
    rb.path('publisherId', params.publisherId, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublisherDto>;
    })
  );
}

getPublisherById.PATH = '/api/publisher/search/{publisherId}';
