/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {PublisherDto} from '../../models/publisher-dto';

export interface UpdatePublisher$Params {
  publisherId: number;
  body: PublisherDto
}

export function updatePublisher(http: HttpClient, rootUrl: string, params: UpdatePublisher$Params, context?: HttpContext): Observable<StrictHttpResponse<PublisherDto>> {
  const rb = new RequestBuilder(rootUrl, updatePublisher.PATH, 'patch');
  if (params) {
    rb.path('publisherId', params.publisherId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublisherDto>;
    })
  );
}

updatePublisher.PATH = '/api/publisher/edit/{publisherId}';
