/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {SeriesDto} from '../../models/series-dto';

export interface AddSeries$Params {
  body: SeriesDto
}

export function addSeries(http: HttpClient, rootUrl: string, params: AddSeries$Params, context?: HttpContext): Observable<StrictHttpResponse<SeriesDto>> {
  const rb = new RequestBuilder(rootUrl, addSeries.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeriesDto>;
    })
  );
}

addSeries.PATH = '/api/series/new';
