/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeriesDto } from '../../models/series-dto';

export interface GetSeries$Params {
  seriesId: number;
}

export function getSeries(http: HttpClient, rootUrl: string, params: GetSeries$Params, context?: HttpContext): Observable<StrictHttpResponse<SeriesDto>> {
  const rb = new RequestBuilder(rootUrl, getSeries.PATH, 'get');
  if (params) {
    rb.path('seriesId', params.seriesId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeriesDto>;
    })
  );
}

getSeries.PATH = '/api/series/search/{seriesId}';
