/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeriesDto } from '../../models/series-dto';

export interface GetAllSeries$Params {
}

export function getAllSeries(http: HttpClient, rootUrl: string, params?: GetAllSeries$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeriesDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllSeries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SeriesDto>>;
    })
  );
}

getAllSeries.PATH = '/api/series/search';
