/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthorDto } from './models/author-dto';
export { BookDto } from './models/book-dto';
export { PublisherDto } from './models/publisher-dto';
export { RelationDto } from './models/relation-dto';
export { SeriesDto } from './models/series-dto';
