/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export {SeriesControllerService} from './services/series-controller.service';
export {RelationControllerService} from './services/relation-controller.service';
export {PublisherControllerService} from './services/publisher-controller.service';
export {BookControllerService} from './services/book-controller.service';
export {AuthorControllerService} from './services/author-controller.service';
