/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createRelation } from '../fn/relation-controller/create-relation';
import { CreateRelation$Params } from '../fn/relation-controller/create-relation';
import { deleteRelation } from '../fn/relation-controller/delete-relation';
import { DeleteRelation$Params } from '../fn/relation-controller/delete-relation';
import { RelationDto } from '../models/relation-dto';

@Injectable({ providedIn: 'root' })
export class RelationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createRelation()` */
  static readonly CreateRelationPath = '/api/relation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRelation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRelation$Response(params: CreateRelation$Params, context?: HttpContext): Observable<StrictHttpResponse<RelationDto>> {
    return createRelation(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRelation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRelation(params: CreateRelation$Params, context?: HttpContext): Observable<RelationDto> {
    return this.createRelation$Response(params, context).pipe(
      map((r: StrictHttpResponse<RelationDto>): RelationDto => r.body)
    );
  }

  /** Path part for operation `deleteRelation()` */
  static readonly DeleteRelationPath = '/api/relation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteRelation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteRelation$Response(params: DeleteRelation$Params, context?: HttpContext): Observable<StrictHttpResponse<RelationDto>> {
    return deleteRelation(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteRelation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteRelation(params: DeleteRelation$Params, context?: HttpContext): Observable<RelationDto> {
    return this.deleteRelation$Response(params, context).pipe(
      map((r: StrictHttpResponse<RelationDto>): RelationDto => r.body)
    );
  }

}
